plugins {
    id 'java'
}

version = ver

tasks.named('jar', Jar) {
    archiveBaseName = 'PvPTime-Mod'
    archiveClassifier = minecraft_version
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : 'Guichaguri',
                'Specification-Version'   : '1',
                'Implementation-Title'    : 'PvPTime',
                'Implementation-Version'  : ver,
                'Implementation-Vendor'   : 'Guichaguri'
        ])
    }

    from(zipTree(project(':common').tasks.named('jar').get().archiveFile))
    from(zipTree(project(':mod:shared').tasks.named('jar').get().archiveFile))
    from(zipTree(project(':mod:fabric').tasks.named('jar').get().archiveFile))
    from(zipTree(project(':mod:neoforge').tasks.named('jar').get().archiveFile))
    from(zipTree(project(':mod:forge').tasks.named('jar').get().archiveFile))

    dependsOn ':common:jar', ':mod:shared:jar', ':mod:fabric:jar', ':mod:neoforge:jar', ':mod:forge:jar'
}
